apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pvc-test

spec:
  rules:
  - host: nttets.selise.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pvc-test
            port:
              number: 80
  tls:
    - hosts:
      - nttets.selise.dev
      secretName: secret-tls