apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: namgyaltobden@gmail.com
    privateKeySecretRef:
      name: http01-cluster-issuer
    solvers:
      - http01:
          ingress:
            class: nginx